<?php

putenv('DISPLAY_ERRORS_DETAILS' . true);

putenv('GERENCIADOR_LOJAS_MYSQL_HOST=localhost');
putenv('GERENCIADOR_LOJAS_MYSQL_PORT=3306');
putenv('GERENCIADOR_LOJAS_MYSQL_DBNAME=gerenciador_lojas');
putenv('GERENCIADOR_LOJAS_MYSQL_USER=root');
putenv('GERENCIADOR_LOJAS_MYSQL_PASSWORD=');
